sizeof_SimpleMemoryAllocator = 20;
alignof_SimpleMemoryAllocator = 4;
soffset_t_size = 4; % bytes


VT_MODEL.VT_VERSION = 4;
VT_MODEL.VT_OPERATOR_CODES = 6;
VT_MODEL.VT_SUBGRAPHS = 8;
VT_MODEL.VT_DESCRIPTION = 10;
VT_MODEL.VT_BUFFERS = 12;
VT_MODEL.VT_METADATA_BUFFER = 14;
VT_MODEL.VT_METADATA = 16;
VT_SUBGRAPHS.VT_TENSORS = 4;
VT_SUBGRAPHS.VT_INPUTS = 6;
VT_SUBGRAPHS.VT_OUTPUTS = 8;
VT_SUBGRAPHS.VT_OPERATORS = 10;
VT_SUBGRAPHS.VT_NAME = 12;
VT_OPERATORS.VT_BUILTIN_CODE = 4;
VT_OPERATORS.VT_CUSTOM_CODE = 6;
VT_OPERATORS.VT_VERSION = 8;
VT_TENSORS.VT_SHAPE = 4;
VT_TENSORS.VT_TYPE = 6;
VT_TENSORS.VT_BUFFER = 8;
VT_TENSORS.VT_NAME = 10;
VT_TENSORS.VT_QUANTIZATION = 12;
VT_TENSORS.VT_IS_VARIABLE = 14;
VT_TENSORS.VT_SPARSITY = 16;
VT_TENSORS.VT_SHAPE_SIGNATURE = 18;


run('BuiltinOperators.m');
