sizeof_SimpleMemoryAllocator = 20;
alignof_SimpleMemoryAllocator = 4;
soffset_t_size = 4; % bytes
sizeof_TFLiteTensor = 768;
alignof_TFLiteTensor = 4;
sizeof_TfLiteAffineQuantization = 12;
alignof_TfLiteAffineQuantization = 4;
sizeof_TFLiteIntArray = 4;
alignof_TFLiteIntArray = 4;

VT_MODEL.VT_VERSION = 4;
VT_MODEL.VT_OPERATOR_CODES = 6;
VT_MODEL.VT_SUBGRAPHS = 8;
VT_MODEL.VT_DESCRIPTION = 10;
VT_MODEL.VT_BUFFERS = 12;
VT_MODEL.VT_METADATA_BUFFER = 14;
VT_MODEL.VT_METADATA = 16;
VT_SUBGRAPHS.VT_TENSORS = 4;
VT_SUBGRAPHS.VT_INPUTS = 6;
VT_SUBGRAPHS.VT_OUTPUTS = 8;
VT_SUBGRAPHS.VT_OPERATORS = 10;
VT_SUBGRAPHS.VT_NAME = 12;
VT_OPERATORS.VT_BUILTIN_CODE = 4;
VT_OPERATORS.VT_CUSTOM_CODE = 6;
VT_OPERATORS.VT_VERSION = 8;
VT_TENSORS.VT_SHAPE = 4;
VT_TENSORS.VT_TYPE = 6;
VT_TENSORS.VT_BUFFER = 8;
VT_TENSORS.VT_NAME = 10;
VT_TENSORS.VT_QUANTIZATION = 12;
VT_TENSORS.VT_IS_VARIABLE = 14;
VT_TENSORS.VT_SPARSITY = 16;
VT_TENSORS.VT_SHAPE_SIGNATURE = 18;
VT_QUANTIZATION.VT_MIN = 4;
VT_QUANTIZATION.VT_MAX = 6;
VT_QUANTIZATION.VT_SCALE = 8;
VT_QUANTIZATION.VT_ZERO_POINT = 10;
VT_QUANTIZATION.VT_DETAILS_TYPE = 12;
VT_QUANTIZATION.VT_DETAILS = 14;
VT_QUANTIZATION.VT_QUANTIZED_DIMENSION = 16;
VT_OPERATOR.VT_OPCODE_INDEX = 4;
VT_OPERATOR.VT_INPUTS = 6;
VT_OPERATOR.VT_OUTPUTS = 8;
VT_OPERATOR.VT_BUILTIN_OPTIONS_TYPE = 10;
VT_OPERATOR.VT_BUILTIN_OPTIONS = 12;
VT_OPERATOR.VT_CUSTOM_OPTIONS = 14;
VT_OPERATOR.VT_CUSTOM_OPTIONS_FORMAT = 16;
VT_OPERATOR.VT_MUTATING_VARIABLE_INPUTS = 18;
VT_OPERATOR.VT_INTERMEDIATES = 20;
VT_BUFFER.VT_DATA = 4;
VT_METADATA.VT_NAME = 4;
VT_METADATA.VT_BUFFER = 6;



run('BuiltinOperators.m');
